[package]
name = "assn-report-monash"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Xingyu Yang <https://github.com/Eryc123Y>"]
license = "MIT"
description = "A report/assignment template for Monash University students with official brand colors and basic theorem environments."
repository = "https://github.com/Eryc123Y/assn-report-monash"
keywords = ["monash", "monash university", "report", "assignment"]
categories = ["paper", "text", "report"]
compiler = "0.13.1"
exclude = ["example/*", "assets/example.bib"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/thumbnail.png"
