[package]
name = "assn-report-monash"
version = "0.1.0"
authors = ["Xingyu Yang <https://github.com/Eryc123Y>"]
license = "MIT"
description = "A report/assignment template for Monash University students with official brand colors and basic theorem environments."
repository = "https://github.com/Eryc123Y/assn-report-monash"
keywords = ["monash", "monash university", "report", "assignment"]
categories = ["Paper", "Text", "Report"]
homepage = "https://github.com/Eryc123Y/assn-report-monash"
documentation = "https://github.com/Eryc123Y/assn-report-monash/blob/main/0.1.0/README.md"
compiler = "0.13.1"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "assets/thumbnail.png"
